name: Build Preview

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZF_NAME: Zusammenfassung # The artifact and output name for this build.
      
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: OST-HS20/latex-parser-action@v1
        id: latexparser
        with:
          latex_file: ${{env.ZF_NAME}}.tex
          command_name: version
          
      # Build latest Latex
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: ${{env.ZF_NAME}}.tex
          
      - name: Upload preview
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.ZF_NAME}} V${{steps.latexparser.outputs.command_value}}
          path: ${{env.ZF_NAME}}.pdf
      
